name: Capture Screenshots with Firefox

on:
  push:
    branches:
      - main

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create custom Docker network
        run: docker network create --subnet=172.18.0.0/16 squid-network

      - name: Pull Squid image
        run: docker pull sameersbn/squid

      - name: Run Squid containers
        run: |
          for i in {1..5}; do
            docker run -d --name squid-$i --net squid-network --ip 172.18.0.$((i+1)) sameersbn/squid
          done

      - name: Install Python 3 and dependencies in Docker containers
        if: ${{ success() }}  # Only execute if all containers are running
        run: |
          for i in {1..5}; do
            docker exec squid-$i apt-get update
            docker exec squid-$i apt-get install -y python3 python3-pip firefox wget tar
            docker exec squid-$i pip3 install selenium
            docker exec squid-$i wget https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
            docker exec squid-$i tar -xvzf geckodriver-v0.31.0-linux64.tar.gz -C /usr/local/bin/
            docker exec squid-$i rm geckodriver-v0.31.0-linux64.tar.gz

            # Create screenshots directory inside Docker container
            docker exec squid-$i mkdir -p /home/ubuntu/screenshots
          done

      - name: Copy Python script into containers
        if: ${{ success() }}  # Only execute if all containers are running
        run: |
          for i in {1..5}; do
            RUNNING=$(docker inspect -f '{{.State.Running}}' squid-$i)
            if [ "$RUNNING" = "true" ]; then
              docker cp .github/workflows/capture_screenshot.py squid-$i:/home/ubuntu/capture_screenshot.py
            else
              echo "Container squid-$i is not running, skipping."
            fi
          done

      - name: Run Python script to capture screenshots with Firefox
        if: ${{ success() }}  # Only execute if all containers are running
        run: |
          for i in {1..5}; do
            RUNNING=$(docker inspect -f '{{.State.Running}}' squid-$i)
            if [ "$RUNNING" = "true" ]; then
              docker exec squid-$i python3 /home/ubuntu/capture_screenshot.py $i
            else
              echo "Container squid-$i is not running, skipping."
            fi
          done

      - name: Copy screenshots from Docker containers
        if: ${{ success() }}  # Only execute if script ran successfully
        run: |
          mkdir -p screenshots

          for i in {1..5}; do
            RUNNING=$(docker inspect -f '{{.State.Running}}' squid-$i)
            if [ "$RUNNING" = "true" ]; then
              docker cp squid-$i:/home/ubuntu/screenshots screenshots/squid-$i
            else
              echo "Container squid-$i is not running, skipping."
            fi
          done

      - name: Archive screenshots as artifacts
        if: ${{ success() }}  # Only archive screenshots if copied successfully
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
